// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cms/common/gender.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_cms_common_gender_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_cms_common_gender_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_cms_common_gender_proto_rawDescGZIP(), []int{0}
}

var File_cms_common_gender_proto protoreflect.FileDescriptor

const file_cms_common_gender_proto_rawDesc = "" +
	"\n" +
	"\x17cms/common/gender.proto\x12\n" +
	"cms.common*\x1e\n" +
	"\x06Gender\x12\b\n" +
	"\x04MALE\x10\x00\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x01b\x06proto3"

var (
	file_cms_common_gender_proto_rawDescOnce sync.Once
	file_cms_common_gender_proto_rawDescData []byte
)

func file_cms_common_gender_proto_rawDescGZIP() []byte {
	file_cms_common_gender_proto_rawDescOnce.Do(func() {
		file_cms_common_gender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_common_gender_proto_rawDesc), len(file_cms_common_gender_proto_rawDesc)))
	})
	return file_cms_common_gender_proto_rawDescData
}

var file_cms_common_gender_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cms_common_gender_proto_goTypes = []any{
	(Gender)(0), // 0: cms.common.Gender
}
var file_cms_common_gender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cms_common_gender_proto_init() }
func file_cms_common_gender_proto_init() {
	if File_cms_common_gender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_common_gender_proto_rawDesc), len(file_cms_common_gender_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cms_common_gender_proto_goTypes,
		DependencyIndexes: file_cms_common_gender_proto_depIdxs,
		EnumInfos:         file_cms_common_gender_proto_enumTypes,
	}.Build()
	File_cms_common_gender_proto = out.File
	file_cms_common_gender_proto_goTypes = nil
	file_cms_common_gender_proto_depIdxs = nil
}
