// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cms/common/v0/biometric_info.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BiometricInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	LeftFaceImageUrl          *string                `protobuf:"bytes,6,opt,name=left_face_image_url,json=leftFaceImageUrl,proto3,oneof" json:"left_face_image_url,omitempty"`
	FrontFaceImageUrl         *string                `protobuf:"bytes,7,opt,name=front_face_image_url,json=frontFaceImageUrl,proto3,oneof" json:"front_face_image_url,omitempty"`
	RightFaceImageUrl         *string                `protobuf:"bytes,8,opt,name=right_face_image_url,json=rightFaceImageUrl,proto3,oneof" json:"right_face_image_url,omitempty"`
	LeftPinkyFingerImageUrl   *string                `protobuf:"bytes,9,opt,name=left_pinky_finger_image_url,json=leftPinkyFingerImageUrl,proto3,oneof" json:"left_pinky_finger_image_url,omitempty"`
	LeftRingFingerImageUrl    *string                `protobuf:"bytes,10,opt,name=left_ring_finger_image_url,json=leftRingFingerImageUrl,proto3,oneof" json:"left_ring_finger_image_url,omitempty"`
	LeftMiddleFingerImageUrl  *string                `protobuf:"bytes,11,opt,name=left_middle_finger_image_url,json=leftMiddleFingerImageUrl,proto3,oneof" json:"left_middle_finger_image_url,omitempty"`
	LeftIndexFingerImageUrl   *string                `protobuf:"bytes,12,opt,name=left_index_finger_image_url,json=leftIndexFingerImageUrl,proto3,oneof" json:"left_index_finger_image_url,omitempty"`
	LeftThumbFingerImageUrl   *string                `protobuf:"bytes,13,opt,name=left_thumb_finger_image_url,json=leftThumbFingerImageUrl,proto3,oneof" json:"left_thumb_finger_image_url,omitempty"`
	RightPinkyFingerImageUrl  *string                `protobuf:"bytes,14,opt,name=right_pinky_finger_image_url,json=rightPinkyFingerImageUrl,proto3,oneof" json:"right_pinky_finger_image_url,omitempty"`
	RightRingFingerImageUrl   *string                `protobuf:"bytes,15,opt,name=right_ring_finger_image_url,json=rightRingFingerImageUrl,proto3,oneof" json:"right_ring_finger_image_url,omitempty"`
	RightMiddleFingerImageUrl *string                `protobuf:"bytes,16,opt,name=right_middle_finger_image_url,json=rightMiddleFingerImageUrl,proto3,oneof" json:"right_middle_finger_image_url,omitempty"`
	RightIndexFingerImageUrl  *string                `protobuf:"bytes,17,opt,name=right_index_finger_image_url,json=rightIndexFingerImageUrl,proto3,oneof" json:"right_index_finger_image_url,omitempty"`
	RightThumbFingerImageUrl  *string                `protobuf:"bytes,18,opt,name=right_thumb_finger_image_url,json=rightThumbFingerImageUrl,proto3,oneof" json:"right_thumb_finger_image_url,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *BiometricInfo) Reset() {
	*x = BiometricInfo{}
	mi := &file_cms_common_v0_biometric_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiometricInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiometricInfo) ProtoMessage() {}

func (x *BiometricInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cms_common_v0_biometric_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiometricInfo.ProtoReflect.Descriptor instead.
func (*BiometricInfo) Descriptor() ([]byte, []int) {
	return file_cms_common_v0_biometric_info_proto_rawDescGZIP(), []int{0}
}

func (x *BiometricInfo) GetLeftFaceImageUrl() string {
	if x != nil && x.LeftFaceImageUrl != nil {
		return *x.LeftFaceImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetFrontFaceImageUrl() string {
	if x != nil && x.FrontFaceImageUrl != nil {
		return *x.FrontFaceImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetRightFaceImageUrl() string {
	if x != nil && x.RightFaceImageUrl != nil {
		return *x.RightFaceImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetLeftPinkyFingerImageUrl() string {
	if x != nil && x.LeftPinkyFingerImageUrl != nil {
		return *x.LeftPinkyFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetLeftRingFingerImageUrl() string {
	if x != nil && x.LeftRingFingerImageUrl != nil {
		return *x.LeftRingFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetLeftMiddleFingerImageUrl() string {
	if x != nil && x.LeftMiddleFingerImageUrl != nil {
		return *x.LeftMiddleFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetLeftIndexFingerImageUrl() string {
	if x != nil && x.LeftIndexFingerImageUrl != nil {
		return *x.LeftIndexFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetLeftThumbFingerImageUrl() string {
	if x != nil && x.LeftThumbFingerImageUrl != nil {
		return *x.LeftThumbFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetRightPinkyFingerImageUrl() string {
	if x != nil && x.RightPinkyFingerImageUrl != nil {
		return *x.RightPinkyFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetRightRingFingerImageUrl() string {
	if x != nil && x.RightRingFingerImageUrl != nil {
		return *x.RightRingFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetRightMiddleFingerImageUrl() string {
	if x != nil && x.RightMiddleFingerImageUrl != nil {
		return *x.RightMiddleFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetRightIndexFingerImageUrl() string {
	if x != nil && x.RightIndexFingerImageUrl != nil {
		return *x.RightIndexFingerImageUrl
	}
	return ""
}

func (x *BiometricInfo) GetRightThumbFingerImageUrl() string {
	if x != nil && x.RightThumbFingerImageUrl != nil {
		return *x.RightThumbFingerImageUrl
	}
	return ""
}

var File_cms_common_v0_biometric_info_proto protoreflect.FileDescriptor

const file_cms_common_v0_biometric_info_proto_rawDesc = "" +
	"\n" +
	"\"cms/common/v0/biometric_info.proto\x12\rcms.common.v0\"\xe6\t\n" +
	"\rBiometricInfo\x122\n" +
	"\x13left_face_image_url\x18\x06 \x01(\tH\x00R\x10leftFaceImageUrl\x88\x01\x01\x124\n" +
	"\x14front_face_image_url\x18\a \x01(\tH\x01R\x11frontFaceImageUrl\x88\x01\x01\x124\n" +
	"\x14right_face_image_url\x18\b \x01(\tH\x02R\x11rightFaceImageUrl\x88\x01\x01\x12A\n" +
	"\x1bleft_pinky_finger_image_url\x18\t \x01(\tH\x03R\x17leftPinkyFingerImageUrl\x88\x01\x01\x12?\n" +
	"\x1aleft_ring_finger_image_url\x18\n" +
	" \x01(\tH\x04R\x16leftRingFingerImageUrl\x88\x01\x01\x12C\n" +
	"\x1cleft_middle_finger_image_url\x18\v \x01(\tH\x05R\x18leftMiddleFingerImageUrl\x88\x01\x01\x12A\n" +
	"\x1bleft_index_finger_image_url\x18\f \x01(\tH\x06R\x17leftIndexFingerImageUrl\x88\x01\x01\x12A\n" +
	"\x1bleft_thumb_finger_image_url\x18\r \x01(\tH\aR\x17leftThumbFingerImageUrl\x88\x01\x01\x12C\n" +
	"\x1cright_pinky_finger_image_url\x18\x0e \x01(\tH\bR\x18rightPinkyFingerImageUrl\x88\x01\x01\x12A\n" +
	"\x1bright_ring_finger_image_url\x18\x0f \x01(\tH\tR\x17rightRingFingerImageUrl\x88\x01\x01\x12E\n" +
	"\x1dright_middle_finger_image_url\x18\x10 \x01(\tH\n" +
	"R\x19rightMiddleFingerImageUrl\x88\x01\x01\x12C\n" +
	"\x1cright_index_finger_image_url\x18\x11 \x01(\tH\vR\x18rightIndexFingerImageUrl\x88\x01\x01\x12C\n" +
	"\x1cright_thumb_finger_image_url\x18\x12 \x01(\tH\fR\x18rightThumbFingerImageUrl\x88\x01\x01B\x16\n" +
	"\x14_left_face_image_urlB\x17\n" +
	"\x15_front_face_image_urlB\x17\n" +
	"\x15_right_face_image_urlB\x1e\n" +
	"\x1c_left_pinky_finger_image_urlB\x1d\n" +
	"\x1b_left_ring_finger_image_urlB\x1f\n" +
	"\x1d_left_middle_finger_image_urlB\x1e\n" +
	"\x1c_left_index_finger_image_urlB\x1e\n" +
	"\x1c_left_thumb_finger_image_urlB\x1f\n" +
	"\x1d_right_pinky_finger_image_urlB\x1e\n" +
	"\x1c_right_ring_finger_image_urlB \n" +
	"\x1e_right_middle_finger_image_urlB\x1f\n" +
	"\x1d_right_index_finger_image_urlB\x1f\n" +
	"\x1d_right_thumb_finger_image_urlb\x06proto3"

var (
	file_cms_common_v0_biometric_info_proto_rawDescOnce sync.Once
	file_cms_common_v0_biometric_info_proto_rawDescData []byte
)

func file_cms_common_v0_biometric_info_proto_rawDescGZIP() []byte {
	file_cms_common_v0_biometric_info_proto_rawDescOnce.Do(func() {
		file_cms_common_v0_biometric_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_common_v0_biometric_info_proto_rawDesc), len(file_cms_common_v0_biometric_info_proto_rawDesc)))
	})
	return file_cms_common_v0_biometric_info_proto_rawDescData
}

var file_cms_common_v0_biometric_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cms_common_v0_biometric_info_proto_goTypes = []any{
	(*BiometricInfo)(nil), // 0: cms.common.v0.BiometricInfo
}
var file_cms_common_v0_biometric_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cms_common_v0_biometric_info_proto_init() }
func file_cms_common_v0_biometric_info_proto_init() {
	if File_cms_common_v0_biometric_info_proto != nil {
		return
	}
	file_cms_common_v0_biometric_info_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_common_v0_biometric_info_proto_rawDesc), len(file_cms_common_v0_biometric_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cms_common_v0_biometric_info_proto_goTypes,
		DependencyIndexes: file_cms_common_v0_biometric_info_proto_depIdxs,
		MessageInfos:      file_cms_common_v0_biometric_info_proto_msgTypes,
	}.Build()
	File_cms_common_v0_biometric_info_proto = out.File
	file_cms_common_v0_biometric_info_proto_goTypes = nil
	file_cms_common_v0_biometric_info_proto_depIdxs = nil
}
