// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cms/common/v0/personal_info.proto

package v0

import (
	common "github.com/EKYCSolutions/cms-integration-api/proto/cms/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalInfo struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	LastNameKhm                        *string                `protobuf:"bytes,1,opt,name=last_name_khm,json=lastNameKhm,proto3,oneof" json:"last_name_khm,omitempty"`
	FirstNameKhm                       *string                `protobuf:"bytes,2,opt,name=first_name_khm,json=firstNameKhm,proto3,oneof" json:"first_name_khm,omitempty"`
	LastNameEng                        *string                `protobuf:"bytes,3,opt,name=last_name_eng,json=lastNameEng,proto3,oneof" json:"last_name_eng,omitempty"`
	FirstNameEng                       *string                `protobuf:"bytes,4,opt,name=first_name_eng,json=firstNameEng,proto3,oneof" json:"first_name_eng,omitempty"`
	WeightInKg                         *uint32                `protobuf:"varint,5,opt,name=weight_in_kg,json=weightInKg,proto3,oneof" json:"weight_in_kg,omitempty"`
	DistinguishableFeaturesDescription *string                `protobuf:"bytes,6,opt,name=distinguishable_features_description,json=distinguishableFeaturesDescription,proto3,oneof" json:"distinguishable_features_description,omitempty"`
	DateOfBirth                        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	NationalityInIso31661Alpha3        *string                `protobuf:"bytes,8,opt,name=nationality_in_iso31661alpha3,json=nationalityInIso31661alpha3,proto3,oneof" json:"nationality_in_iso31661alpha3,omitempty"`
	Ethnicity                          *string                `protobuf:"bytes,9,opt,name=ethnicity,proto3,oneof" json:"ethnicity,omitempty"`
	NationalId                         *string                `protobuf:"bytes,10,opt,name=national_id,json=nationalId,proto3,oneof" json:"national_id,omitempty"`
	PassportNumber                     *string                `protobuf:"bytes,11,opt,name=passport_number,json=passportNumber,proto3,oneof" json:"passport_number,omitempty"`
	Sex                                *common.Gender         `protobuf:"varint,12,opt,name=sex,proto3,enum=cms.common.Gender,oneof" json:"sex,omitempty"`
	HeightInCm                         *uint32                `protobuf:"varint,13,opt,name=height_in_cm,json=heightInCm,proto3,oneof" json:"height_in_cm,omitempty"`
	BirthPlaceProvince                 *string                `protobuf:"bytes,14,opt,name=birth_place_province,json=birthPlaceProvince,proto3,oneof" json:"birth_place_province,omitempty"`
	BirthPlaceDistrict                 *string                `protobuf:"bytes,15,opt,name=birth_place_district,json=birthPlaceDistrict,proto3,oneof" json:"birth_place_district,omitempty"`
	BirthPlaceCommune                  *string                `protobuf:"bytes,16,opt,name=birth_place_commune,json=birthPlaceCommune,proto3,oneof" json:"birth_place_commune,omitempty"`
	BirthPlaceVillage                  *string                `protobuf:"bytes,17,opt,name=birth_place_village,json=birthPlaceVillage,proto3,oneof" json:"birth_place_village,omitempty"`
	BirthPlaceHouseLabel               *string                `protobuf:"bytes,18,opt,name=birth_place_house_label,json=birthPlaceHouseLabel,proto3,oneof" json:"birth_place_house_label,omitempty"`
	BirthPlaceStreetLabel              *string                `protobuf:"bytes,19,opt,name=birth_place_street_label,json=birthPlaceStreetLabel,proto3,oneof" json:"birth_place_street_label,omitempty"`
	CurrentLivingAddressProvince       *string                `protobuf:"bytes,20,opt,name=current_living_address_province,json=currentLivingAddressProvince,proto3,oneof" json:"current_living_address_province,omitempty"`
	CurrentLivingAddressDistrict       *string                `protobuf:"bytes,21,opt,name=current_living_address_district,json=currentLivingAddressDistrict,proto3,oneof" json:"current_living_address_district,omitempty"`
	CurrentLivingAddressCommune        *string                `protobuf:"bytes,22,opt,name=current_living_address_commune,json=currentLivingAddressCommune,proto3,oneof" json:"current_living_address_commune,omitempty"`
	CurrentLivingAddressVillage        *string                `protobuf:"bytes,23,opt,name=current_living_address_village,json=currentLivingAddressVillage,proto3,oneof" json:"current_living_address_village,omitempty"`
	CurrentLivingAddressHouseLabel     *string                `protobuf:"bytes,24,opt,name=current_living_address_house_label,json=currentLivingAddressHouseLabel,proto3,oneof" json:"current_living_address_house_label,omitempty"`
	CurrentLivingAddressStreetLabel    *string                `protobuf:"bytes,25,opt,name=current_living_address_street_label,json=currentLivingAddressStreetLabel,proto3,oneof" json:"current_living_address_street_label,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_cms_common_v0_personal_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cms_common_v0_personal_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_cms_common_v0_personal_info_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalInfo) GetLastNameKhm() string {
	if x != nil && x.LastNameKhm != nil {
		return *x.LastNameKhm
	}
	return ""
}

func (x *PersonalInfo) GetFirstNameKhm() string {
	if x != nil && x.FirstNameKhm != nil {
		return *x.FirstNameKhm
	}
	return ""
}

func (x *PersonalInfo) GetLastNameEng() string {
	if x != nil && x.LastNameEng != nil {
		return *x.LastNameEng
	}
	return ""
}

func (x *PersonalInfo) GetFirstNameEng() string {
	if x != nil && x.FirstNameEng != nil {
		return *x.FirstNameEng
	}
	return ""
}

func (x *PersonalInfo) GetWeightInKg() uint32 {
	if x != nil && x.WeightInKg != nil {
		return *x.WeightInKg
	}
	return 0
}

func (x *PersonalInfo) GetDistinguishableFeaturesDescription() string {
	if x != nil && x.DistinguishableFeaturesDescription != nil {
		return *x.DistinguishableFeaturesDescription
	}
	return ""
}

func (x *PersonalInfo) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *PersonalInfo) GetNationalityInIso31661Alpha3() string {
	if x != nil && x.NationalityInIso31661Alpha3 != nil {
		return *x.NationalityInIso31661Alpha3
	}
	return ""
}

func (x *PersonalInfo) GetEthnicity() string {
	if x != nil && x.Ethnicity != nil {
		return *x.Ethnicity
	}
	return ""
}

func (x *PersonalInfo) GetNationalId() string {
	if x != nil && x.NationalId != nil {
		return *x.NationalId
	}
	return ""
}

func (x *PersonalInfo) GetPassportNumber() string {
	if x != nil && x.PassportNumber != nil {
		return *x.PassportNumber
	}
	return ""
}

func (x *PersonalInfo) GetSex() common.Gender {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return common.Gender(0)
}

func (x *PersonalInfo) GetHeightInCm() uint32 {
	if x != nil && x.HeightInCm != nil {
		return *x.HeightInCm
	}
	return 0
}

func (x *PersonalInfo) GetBirthPlaceProvince() string {
	if x != nil && x.BirthPlaceProvince != nil {
		return *x.BirthPlaceProvince
	}
	return ""
}

func (x *PersonalInfo) GetBirthPlaceDistrict() string {
	if x != nil && x.BirthPlaceDistrict != nil {
		return *x.BirthPlaceDistrict
	}
	return ""
}

func (x *PersonalInfo) GetBirthPlaceCommune() string {
	if x != nil && x.BirthPlaceCommune != nil {
		return *x.BirthPlaceCommune
	}
	return ""
}

func (x *PersonalInfo) GetBirthPlaceVillage() string {
	if x != nil && x.BirthPlaceVillage != nil {
		return *x.BirthPlaceVillage
	}
	return ""
}

func (x *PersonalInfo) GetBirthPlaceHouseLabel() string {
	if x != nil && x.BirthPlaceHouseLabel != nil {
		return *x.BirthPlaceHouseLabel
	}
	return ""
}

func (x *PersonalInfo) GetBirthPlaceStreetLabel() string {
	if x != nil && x.BirthPlaceStreetLabel != nil {
		return *x.BirthPlaceStreetLabel
	}
	return ""
}

func (x *PersonalInfo) GetCurrentLivingAddressProvince() string {
	if x != nil && x.CurrentLivingAddressProvince != nil {
		return *x.CurrentLivingAddressProvince
	}
	return ""
}

func (x *PersonalInfo) GetCurrentLivingAddressDistrict() string {
	if x != nil && x.CurrentLivingAddressDistrict != nil {
		return *x.CurrentLivingAddressDistrict
	}
	return ""
}

func (x *PersonalInfo) GetCurrentLivingAddressCommune() string {
	if x != nil && x.CurrentLivingAddressCommune != nil {
		return *x.CurrentLivingAddressCommune
	}
	return ""
}

func (x *PersonalInfo) GetCurrentLivingAddressVillage() string {
	if x != nil && x.CurrentLivingAddressVillage != nil {
		return *x.CurrentLivingAddressVillage
	}
	return ""
}

func (x *PersonalInfo) GetCurrentLivingAddressHouseLabel() string {
	if x != nil && x.CurrentLivingAddressHouseLabel != nil {
		return *x.CurrentLivingAddressHouseLabel
	}
	return ""
}

func (x *PersonalInfo) GetCurrentLivingAddressStreetLabel() string {
	if x != nil && x.CurrentLivingAddressStreetLabel != nil {
		return *x.CurrentLivingAddressStreetLabel
	}
	return ""
}

var File_cms_common_v0_personal_info_proto protoreflect.FileDescriptor

const file_cms_common_v0_personal_info_proto_rawDesc = "" +
	"\n" +
	"!cms/common/v0/personal_info.proto\x12\rcms.common.v0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17cms/common/gender.proto\"\xa8\x10\n" +
	"\fPersonalInfo\x12'\n" +
	"\rlast_name_khm\x18\x01 \x01(\tH\x00R\vlastNameKhm\x88\x01\x01\x12)\n" +
	"\x0efirst_name_khm\x18\x02 \x01(\tH\x01R\ffirstNameKhm\x88\x01\x01\x12'\n" +
	"\rlast_name_eng\x18\x03 \x01(\tH\x02R\vlastNameEng\x88\x01\x01\x12)\n" +
	"\x0efirst_name_eng\x18\x04 \x01(\tH\x03R\ffirstNameEng\x88\x01\x01\x12%\n" +
	"\fweight_in_kg\x18\x05 \x01(\rH\x04R\n" +
	"weightInKg\x88\x01\x01\x12U\n" +
	"$distinguishable_features_description\x18\x06 \x01(\tH\x05R\"distinguishableFeaturesDescription\x88\x01\x01\x12C\n" +
	"\rdate_of_birth\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x06R\vdateOfBirth\x88\x01\x01\x12G\n" +
	"\x1dnationality_in_iso31661alpha3\x18\b \x01(\tH\aR\x1bnationalityInIso31661alpha3\x88\x01\x01\x12!\n" +
	"\tethnicity\x18\t \x01(\tH\bR\tethnicity\x88\x01\x01\x12$\n" +
	"\vnational_id\x18\n" +
	" \x01(\tH\tR\n" +
	"nationalId\x88\x01\x01\x12,\n" +
	"\x0fpassport_number\x18\v \x01(\tH\n" +
	"R\x0epassportNumber\x88\x01\x01\x12)\n" +
	"\x03sex\x18\f \x01(\x0e2\x12.cms.common.GenderH\vR\x03sex\x88\x01\x01\x12%\n" +
	"\fheight_in_cm\x18\r \x01(\rH\fR\n" +
	"heightInCm\x88\x01\x01\x125\n" +
	"\x14birth_place_province\x18\x0e \x01(\tH\rR\x12birthPlaceProvince\x88\x01\x01\x125\n" +
	"\x14birth_place_district\x18\x0f \x01(\tH\x0eR\x12birthPlaceDistrict\x88\x01\x01\x123\n" +
	"\x13birth_place_commune\x18\x10 \x01(\tH\x0fR\x11birthPlaceCommune\x88\x01\x01\x123\n" +
	"\x13birth_place_village\x18\x11 \x01(\tH\x10R\x11birthPlaceVillage\x88\x01\x01\x12:\n" +
	"\x17birth_place_house_label\x18\x12 \x01(\tH\x11R\x14birthPlaceHouseLabel\x88\x01\x01\x12<\n" +
	"\x18birth_place_street_label\x18\x13 \x01(\tH\x12R\x15birthPlaceStreetLabel\x88\x01\x01\x12J\n" +
	"\x1fcurrent_living_address_province\x18\x14 \x01(\tH\x13R\x1ccurrentLivingAddressProvince\x88\x01\x01\x12J\n" +
	"\x1fcurrent_living_address_district\x18\x15 \x01(\tH\x14R\x1ccurrentLivingAddressDistrict\x88\x01\x01\x12H\n" +
	"\x1ecurrent_living_address_commune\x18\x16 \x01(\tH\x15R\x1bcurrentLivingAddressCommune\x88\x01\x01\x12H\n" +
	"\x1ecurrent_living_address_village\x18\x17 \x01(\tH\x16R\x1bcurrentLivingAddressVillage\x88\x01\x01\x12O\n" +
	"\"current_living_address_house_label\x18\x18 \x01(\tH\x17R\x1ecurrentLivingAddressHouseLabel\x88\x01\x01\x12Q\n" +
	"#current_living_address_street_label\x18\x19 \x01(\tH\x18R\x1fcurrentLivingAddressStreetLabel\x88\x01\x01B\x10\n" +
	"\x0e_last_name_khmB\x11\n" +
	"\x0f_first_name_khmB\x10\n" +
	"\x0e_last_name_engB\x11\n" +
	"\x0f_first_name_engB\x0f\n" +
	"\r_weight_in_kgB'\n" +
	"%_distinguishable_features_descriptionB\x10\n" +
	"\x0e_date_of_birthB \n" +
	"\x1e_nationality_in_iso31661alpha3B\f\n" +
	"\n" +
	"_ethnicityB\x0e\n" +
	"\f_national_idB\x12\n" +
	"\x10_passport_numberB\x06\n" +
	"\x04_sexB\x0f\n" +
	"\r_height_in_cmB\x17\n" +
	"\x15_birth_place_provinceB\x17\n" +
	"\x15_birth_place_districtB\x16\n" +
	"\x14_birth_place_communeB\x16\n" +
	"\x14_birth_place_villageB\x1a\n" +
	"\x18_birth_place_house_labelB\x1b\n" +
	"\x19_birth_place_street_labelB\"\n" +
	" _current_living_address_provinceB\"\n" +
	" _current_living_address_districtB!\n" +
	"\x1f_current_living_address_communeB!\n" +
	"\x1f_current_living_address_villageB%\n" +
	"#_current_living_address_house_labelB&\n" +
	"$_current_living_address_street_labelb\x06proto3"

var (
	file_cms_common_v0_personal_info_proto_rawDescOnce sync.Once
	file_cms_common_v0_personal_info_proto_rawDescData []byte
)

func file_cms_common_v0_personal_info_proto_rawDescGZIP() []byte {
	file_cms_common_v0_personal_info_proto_rawDescOnce.Do(func() {
		file_cms_common_v0_personal_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_common_v0_personal_info_proto_rawDesc), len(file_cms_common_v0_personal_info_proto_rawDesc)))
	})
	return file_cms_common_v0_personal_info_proto_rawDescData
}

var file_cms_common_v0_personal_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cms_common_v0_personal_info_proto_goTypes = []any{
	(*PersonalInfo)(nil),          // 0: cms.common.v0.PersonalInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(common.Gender)(0),            // 2: cms.common.Gender
}
var file_cms_common_v0_personal_info_proto_depIdxs = []int32{
	1, // 0: cms.common.v0.PersonalInfo.date_of_birth:type_name -> google.protobuf.Timestamp
	2, // 1: cms.common.v0.PersonalInfo.sex:type_name -> cms.common.Gender
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cms_common_v0_personal_info_proto_init() }
func file_cms_common_v0_personal_info_proto_init() {
	if File_cms_common_v0_personal_info_proto != nil {
		return
	}
	file_cms_common_v0_personal_info_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_common_v0_personal_info_proto_rawDesc), len(file_cms_common_v0_personal_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cms_common_v0_personal_info_proto_goTypes,
		DependencyIndexes: file_cms_common_v0_personal_info_proto_depIdxs,
		MessageInfos:      file_cms_common_v0_personal_info_proto_msgTypes,
	}.Build()
	File_cms_common_v0_personal_info_proto = out.File
	file_cms_common_v0_personal_info_proto_goTypes = nil
	file_cms_common_v0_personal_info_proto_depIdxs = nil
}
