// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cms/common/v0/search_request_filter.proto

package v0

import (
	common "github.com/EKYCSolutions/cms-integration-api/proto/cms/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequestFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	IdentityIds    []string               `protobuf:"bytes,2,rep,name=identity_ids,json=identityIds,proto3" json:"identity_ids,omitempty"`
	MinHeightInCm  *uint32                `protobuf:"varint,3,opt,name=min_height_in_cm,json=minHeightInCm,proto3,oneof" json:"min_height_in_cm,omitempty"`
	MaxHeightInCm  *uint32                `protobuf:"varint,4,opt,name=max_height_in_cm,json=maxHeightInCm,proto3,oneof" json:"max_height_in_cm,omitempty"`
	Gender         *common.Gender         `protobuf:"varint,5,opt,name=gender,proto3,enum=cms.common.Gender,oneof" json:"gender,omitempty"`
	NationalId     *string                `protobuf:"bytes,6,opt,name=national_id,json=nationalId,proto3,oneof" json:"national_id,omitempty"`
	PassportNumber *string                `protobuf:"bytes,7,opt,name=passport_number,json=passportNumber,proto3,oneof" json:"passport_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequestFilter) Reset() {
	*x = SearchRequestFilter{}
	mi := &file_cms_common_v0_search_request_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequestFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequestFilter) ProtoMessage() {}

func (x *SearchRequestFilter) ProtoReflect() protoreflect.Message {
	mi := &file_cms_common_v0_search_request_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequestFilter.ProtoReflect.Descriptor instead.
func (*SearchRequestFilter) Descriptor() ([]byte, []int) {
	return file_cms_common_v0_search_request_filter_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequestFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SearchRequestFilter) GetIdentityIds() []string {
	if x != nil {
		return x.IdentityIds
	}
	return nil
}

func (x *SearchRequestFilter) GetMinHeightInCm() uint32 {
	if x != nil && x.MinHeightInCm != nil {
		return *x.MinHeightInCm
	}
	return 0
}

func (x *SearchRequestFilter) GetMaxHeightInCm() uint32 {
	if x != nil && x.MaxHeightInCm != nil {
		return *x.MaxHeightInCm
	}
	return 0
}

func (x *SearchRequestFilter) GetGender() common.Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return common.Gender(0)
}

func (x *SearchRequestFilter) GetNationalId() string {
	if x != nil && x.NationalId != nil {
		return *x.NationalId
	}
	return ""
}

func (x *SearchRequestFilter) GetPassportNumber() string {
	if x != nil && x.PassportNumber != nil {
		return *x.PassportNumber
	}
	return ""
}

var File_cms_common_v0_search_request_filter_proto protoreflect.FileDescriptor

const file_cms_common_v0_search_request_filter_proto_rawDesc = "" +
	"\n" +
	")cms/common/v0/search_request_filter.proto\x12\rcms.common.v0\x1a\x17cms/common/gender.proto\"\x94\x03\n" +
	"\x13SearchRequestFilter\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12!\n" +
	"\fidentity_ids\x18\x02 \x03(\tR\videntityIds\x12,\n" +
	"\x10min_height_in_cm\x18\x03 \x01(\rH\x01R\rminHeightInCm\x88\x01\x01\x12,\n" +
	"\x10max_height_in_cm\x18\x04 \x01(\rH\x02R\rmaxHeightInCm\x88\x01\x01\x12/\n" +
	"\x06gender\x18\x05 \x01(\x0e2\x12.cms.common.GenderH\x03R\x06gender\x88\x01\x01\x12$\n" +
	"\vnational_id\x18\x06 \x01(\tH\x04R\n" +
	"nationalId\x88\x01\x01\x12,\n" +
	"\x0fpassport_number\x18\a \x01(\tH\x05R\x0epassportNumber\x88\x01\x01B\a\n" +
	"\x05_nameB\x13\n" +
	"\x11_min_height_in_cmB\x13\n" +
	"\x11_max_height_in_cmB\t\n" +
	"\a_genderB\x0e\n" +
	"\f_national_idB\x12\n" +
	"\x10_passport_numberb\x06proto3"

var (
	file_cms_common_v0_search_request_filter_proto_rawDescOnce sync.Once
	file_cms_common_v0_search_request_filter_proto_rawDescData []byte
)

func file_cms_common_v0_search_request_filter_proto_rawDescGZIP() []byte {
	file_cms_common_v0_search_request_filter_proto_rawDescOnce.Do(func() {
		file_cms_common_v0_search_request_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_common_v0_search_request_filter_proto_rawDesc), len(file_cms_common_v0_search_request_filter_proto_rawDesc)))
	})
	return file_cms_common_v0_search_request_filter_proto_rawDescData
}

var file_cms_common_v0_search_request_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cms_common_v0_search_request_filter_proto_goTypes = []any{
	(*SearchRequestFilter)(nil), // 0: cms.common.v0.SearchRequestFilter
	(common.Gender)(0),          // 1: cms.common.Gender
}
var file_cms_common_v0_search_request_filter_proto_depIdxs = []int32{
	1, // 0: cms.common.v0.SearchRequestFilter.gender:type_name -> cms.common.Gender
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cms_common_v0_search_request_filter_proto_init() }
func file_cms_common_v0_search_request_filter_proto_init() {
	if File_cms_common_v0_search_request_filter_proto != nil {
		return
	}
	file_cms_common_v0_search_request_filter_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_common_v0_search_request_filter_proto_rawDesc), len(file_cms_common_v0_search_request_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cms_common_v0_search_request_filter_proto_goTypes,
		DependencyIndexes: file_cms_common_v0_search_request_filter_proto_depIdxs,
		MessageInfos:      file_cms_common_v0_search_request_filter_proto_msgTypes,
	}.Build()
	File_cms_common_v0_search_request_filter_proto = out.File
	file_cms_common_v0_search_request_filter_proto_goTypes = nil
	file_cms_common_v0_search_request_filter_proto_depIdxs = nil
}
