// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gdi/apis/v0/identity.proto

package v0

import (
	common "github.com/EKYCSolutions/cms-integration-api/proto/gdi/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchIdentityRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`                                                                        //* name to search, could be in full name or partial. eg: socret
	Age                    *uint32                `protobuf:"varint,2,opt,name=age,proto3,oneof" json:"age,omitempty"`                                                                         //* age to filter. eg: 32
	HeightInCm             *uint32                `protobuf:"varint,3,opt,name=height_in_cm,json=heightInCm,proto3,oneof" json:"height_in_cm,omitempty"`                                       //* height to filter. eg: 160
	Gender                 *common.Gender         `protobuf:"varint,4,opt,name=gender,proto3,enum=gdi.common.Gender,oneof" json:"gender,omitempty"`                                            //* height to filter. eg: MALE
	LeftFaceImage          []byte                 `protobuf:"bytes,5,opt,name=left_face_image,json=leftFaceImage,proto3,oneof" json:"left_face_image,omitempty"`                               //* left face image to filter. eg: [ensure jpeg file]
	FrontFaceImage         []byte                 `protobuf:"bytes,6,opt,name=front_face_image,json=frontFaceImage,proto3,oneof" json:"front_face_image,omitempty"`                            //* front face image to filter. eg: [ensure jpeg file]
	RightFaceImage         []byte                 `protobuf:"bytes,7,opt,name=right_face_image,json=rightFaceImage,proto3,oneof" json:"right_face_image,omitempty"`                            //* right face image to filter. eg: [ensure jpeg file]
	LeftPinkyFingerImage   []byte                 `protobuf:"bytes,8,opt,name=left_pinky_finger_image,json=leftPinkyFingerImage,proto3,oneof" json:"left_pinky_finger_image,omitempty"`        //* left pinky finger image to filter. eg: [ensure jpeg file]
	LeftRingFingerImage    []byte                 `protobuf:"bytes,9,opt,name=left_ring_finger_image,json=leftRingFingerImage,proto3,oneof" json:"left_ring_finger_image,omitempty"`           //* left ring finger image to filter. eg: [ensure jpeg file]
	LeftMiddleFingerImage  []byte                 `protobuf:"bytes,10,opt,name=left_middle_finger_image,json=leftMiddleFingerImage,proto3,oneof" json:"left_middle_finger_image,omitempty"`    //* left middle finger image to filter. eg: [ensure jpeg file]
	LeftIndexFingerImage   []byte                 `protobuf:"bytes,11,opt,name=left_index_finger_image,json=leftIndexFingerImage,proto3,oneof" json:"left_index_finger_image,omitempty"`       //* left index finger image image to filter. eg: [ensure jpeg file]
	LeftThumbFingerImage   []byte                 `protobuf:"bytes,12,opt,name=left_thumb_finger_image,json=leftThumbFingerImage,proto3,oneof" json:"left_thumb_finger_image,omitempty"`       //* left thumb finger image image to filter. eg: [ensure jpeg file]
	RightPinkyFingerImage  []byte                 `protobuf:"bytes,13,opt,name=right_pinky_finger_image,json=rightPinkyFingerImage,proto3,oneof" json:"right_pinky_finger_image,omitempty"`    //* right pinky finger image image to filter. eg: [ensure jpeg file]
	RightRingFingerImage   []byte                 `protobuf:"bytes,14,opt,name=right_ring_finger_image,json=rightRingFingerImage,proto3,oneof" json:"right_ring_finger_image,omitempty"`       //* right ring finger image image to filter. eg: [ensure jpeg file]
	RightMiddleFingerImage []byte                 `protobuf:"bytes,15,opt,name=right_middle_finger_image,json=rightMiddleFingerImage,proto3,oneof" json:"right_middle_finger_image,omitempty"` //* right middle finger image image to filter. eg: [ensure jpeg file]
	RightIndexFingerImage  []byte                 `protobuf:"bytes,16,opt,name=right_index_finger_image,json=rightIndexFingerImage,proto3,oneof" json:"right_index_finger_image,omitempty"`    //* right index finger image image to filter. eg: [ensure jpeg file]
	RightThumbFingerImage  []byte                 `protobuf:"bytes,17,opt,name=right_thumb_finger_image,json=rightThumbFingerImage,proto3,oneof" json:"right_thumb_finger_image,omitempty"`    //* right thumb finger image image to filter. eg: [ensure jpeg file]
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SearchIdentityRequest) Reset() {
	*x = SearchIdentityRequest{}
	mi := &file_gdi_apis_v0_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIdentityRequest) ProtoMessage() {}

func (x *SearchIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdi_apis_v0_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIdentityRequest.ProtoReflect.Descriptor instead.
func (*SearchIdentityRequest) Descriptor() ([]byte, []int) {
	return file_gdi_apis_v0_identity_proto_rawDescGZIP(), []int{0}
}

func (x *SearchIdentityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SearchIdentityRequest) GetAge() uint32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *SearchIdentityRequest) GetHeightInCm() uint32 {
	if x != nil && x.HeightInCm != nil {
		return *x.HeightInCm
	}
	return 0
}

func (x *SearchIdentityRequest) GetGender() common.Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return common.Gender(0)
}

func (x *SearchIdentityRequest) GetLeftFaceImage() []byte {
	if x != nil {
		return x.LeftFaceImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetFrontFaceImage() []byte {
	if x != nil {
		return x.FrontFaceImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetRightFaceImage() []byte {
	if x != nil {
		return x.RightFaceImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetLeftPinkyFingerImage() []byte {
	if x != nil {
		return x.LeftPinkyFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetLeftRingFingerImage() []byte {
	if x != nil {
		return x.LeftRingFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetLeftMiddleFingerImage() []byte {
	if x != nil {
		return x.LeftMiddleFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetLeftIndexFingerImage() []byte {
	if x != nil {
		return x.LeftIndexFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetLeftThumbFingerImage() []byte {
	if x != nil {
		return x.LeftThumbFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetRightPinkyFingerImage() []byte {
	if x != nil {
		return x.RightPinkyFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetRightRingFingerImage() []byte {
	if x != nil {
		return x.RightRingFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetRightMiddleFingerImage() []byte {
	if x != nil {
		return x.RightMiddleFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetRightIndexFingerImage() []byte {
	if x != nil {
		return x.RightIndexFingerImage
	}
	return nil
}

func (x *SearchIdentityRequest) GetRightThumbFingerImage() []byte {
	if x != nil {
		return x.RightThumbFingerImage
	}
	return nil
}

type SearchIdentityResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	LastNameKhm                        *string                `protobuf:"bytes,1,opt,name=last_name_khm,json=lastNameKhm,proto3,oneof" json:"last_name_khm,omitempty"`                                                                      //* last name in khmer. eg: សុក្រិត
	FirstNameKhm                       *string                `protobuf:"bytes,2,opt,name=first_name_khm,json=firstNameKhm,proto3,oneof" json:"first_name_khm,omitempty"`                                                                   //* first name in khmer. eg: លី
	LastNameEng                        *string                `protobuf:"bytes,3,opt,name=last_name_eng,json=lastNameEng,proto3,oneof" json:"last_name_eng,omitempty"`                                                                      //* last name in english. eg: socret
	FirstNameEng                       *string                `protobuf:"bytes,4,opt,name=first_name_eng,json=firstNameEng,proto3,oneof" json:"first_name_eng,omitempty"`                                                                   //* first name in english. eg: ly
	WeightInKg                         *uint32                `protobuf:"varint,5,opt,name=weight_in_kg,json=weightInKg,proto3,oneof" json:"weight_in_kg,omitempty"`                                                                        //* weight in kg. eg: 60
	DistinguishableFeaturesDescription *string                `protobuf:"bytes,6,opt,name=distinguishable_features_description,json=distinguishableFeaturesDescription,proto3,oneof" json:"distinguishable_features_description,omitempty"` //* the person identifiable features. eg: has tattoo on left cheek
	DateOfBirth                        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`                                                                      //* date of birth: 1990-01-01T00:30:22Z
	NationalityInIso31661Alpha3        *string                `protobuf:"bytes,8,opt,name=nationality_in_iso31661alpha3,json=nationalityInIso31661alpha3,proto3,oneof" json:"nationality_in_iso31661alpha3,omitempty"`                      //* nationality in iso31661 alhpa3 format. eg: afg (afghanistan)
	Ethnicity                          *string                `protobuf:"bytes,9,opt,name=ethnicity,proto3,oneof" json:"ethnicity,omitempty"`                                                                                               //* the person ethnicity, eg: asian
	NationalId                         *string                `protobuf:"bytes,10,opt,name=national_id,json=nationalId,proto3,oneof" json:"national_id,omitempty"`                                                                          //* national id, eg: 121233330
	PassportNumber                     *string                `protobuf:"bytes,11,opt,name=passport_number,json=passportNumber,proto3,oneof" json:"passport_number,omitempty"`                                                              //* passport number, eg: 121233330
	Sex                                *common.Gender         `protobuf:"varint,12,opt,name=sex,proto3,enum=gdi.common.Gender,oneof" json:"sex,omitempty"`                                                                                  //* the person gender, eg: FEMALE
	HeightInCm                         *uint32                `protobuf:"varint,13,opt,name=height_in_cm,json=heightInCm,proto3,oneof" json:"height_in_cm,omitempty"`                                                                       //* the person height in cm, eg: 160
	BirthPlaceProvince                 *string                `protobuf:"bytes,14,opt,name=birth_place_province,json=birthPlaceProvince,proto3,oneof" json:"birth_place_province,omitempty"`                                                //* eg: Phnom Penh
	BirthPlaceDistrict                 *string                `protobuf:"bytes,15,opt,name=birth_place_district,json=birthPlaceDistrict,proto3,oneof" json:"birth_place_district,omitempty"`                                                //* eg: Monorom
	BirthPlaceCommune                  *string                `protobuf:"bytes,16,opt,name=birth_place_commune,json=birthPlaceCommune,proto3,oneof" json:"birth_place_commune,omitempty"`                                                   //* eg: Psa Tmey 2
	BirthPlaceVillage                  *string                `protobuf:"bytes,17,opt,name=birth_place_village,json=birthPlaceVillage,proto3,oneof" json:"birth_place_village,omitempty"`                                                   //* eg: Phum 99
	BirthPlaceHouseLabel               *string                `protobuf:"bytes,18,opt,name=birth_place_house_label,json=birthPlaceHouseLabel,proto3,oneof" json:"birth_place_house_label,omitempty"`                                        //* eg: tk, 256
	BirthPlaceStreetLabel              *string                `protobuf:"bytes,19,opt,name=birth_place_street_label,json=birthPlaceStreetLabel,proto3,oneof" json:"birth_place_street_label,omitempty"`                                     //* eg: st952
	CurrentLivingAddressProvince       *string                `protobuf:"bytes,20,opt,name=current_living_address_province,json=currentLivingAddressProvince,proto3,oneof" json:"current_living_address_province,omitempty"`                //* eg: Phnom Penh
	CurrentLivingAddressDistrict       *string                `protobuf:"bytes,21,opt,name=current_living_address_district,json=currentLivingAddressDistrict,proto3,oneof" json:"current_living_address_district,omitempty"`                //* eg: Monorom
	CurrentLivingAddressCommune        *string                `protobuf:"bytes,22,opt,name=current_living_address_commune,json=currentLivingAddressCommune,proto3,oneof" json:"current_living_address_commune,omitempty"`                   //* eg: Psa Tmey 2
	CurrentLivingAddressVillage        *string                `protobuf:"bytes,23,opt,name=current_living_address_village,json=currentLivingAddressVillage,proto3,oneof" json:"current_living_address_village,omitempty"`                   //* eg: Phum 99
	CurrentLivingAddressHouseLabel     *string                `protobuf:"bytes,24,opt,name=current_living_address_house_label,json=currentLivingAddressHouseLabel,proto3,oneof" json:"current_living_address_house_label,omitempty"`        //* eg: tk, 256
	CurrentLivingAddressStreetLabel    *string                `protobuf:"bytes,25,opt,name=current_living_address_street_label,json=currentLivingAddressStreetLabel,proto3,oneof" json:"current_living_address_street_label,omitempty"`     //* eg: st952
	ProfileImageDownloadUrl            *string                `protobuf:"bytes,26,opt,name=profile_image_download_url,json=profileImageDownloadUrl,proto3,oneof" json:"profile_image_download_url,omitempty"`                               //* eg: https://acme.org/identity/1111-1111-1111-1111/profile-image.jpg
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *SearchIdentityResponse) Reset() {
	*x = SearchIdentityResponse{}
	mi := &file_gdi_apis_v0_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIdentityResponse) ProtoMessage() {}

func (x *SearchIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gdi_apis_v0_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIdentityResponse.ProtoReflect.Descriptor instead.
func (*SearchIdentityResponse) Descriptor() ([]byte, []int) {
	return file_gdi_apis_v0_identity_proto_rawDescGZIP(), []int{1}
}

func (x *SearchIdentityResponse) GetLastNameKhm() string {
	if x != nil && x.LastNameKhm != nil {
		return *x.LastNameKhm
	}
	return ""
}

func (x *SearchIdentityResponse) GetFirstNameKhm() string {
	if x != nil && x.FirstNameKhm != nil {
		return *x.FirstNameKhm
	}
	return ""
}

func (x *SearchIdentityResponse) GetLastNameEng() string {
	if x != nil && x.LastNameEng != nil {
		return *x.LastNameEng
	}
	return ""
}

func (x *SearchIdentityResponse) GetFirstNameEng() string {
	if x != nil && x.FirstNameEng != nil {
		return *x.FirstNameEng
	}
	return ""
}

func (x *SearchIdentityResponse) GetWeightInKg() uint32 {
	if x != nil && x.WeightInKg != nil {
		return *x.WeightInKg
	}
	return 0
}

func (x *SearchIdentityResponse) GetDistinguishableFeaturesDescription() string {
	if x != nil && x.DistinguishableFeaturesDescription != nil {
		return *x.DistinguishableFeaturesDescription
	}
	return ""
}

func (x *SearchIdentityResponse) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *SearchIdentityResponse) GetNationalityInIso31661Alpha3() string {
	if x != nil && x.NationalityInIso31661Alpha3 != nil {
		return *x.NationalityInIso31661Alpha3
	}
	return ""
}

func (x *SearchIdentityResponse) GetEthnicity() string {
	if x != nil && x.Ethnicity != nil {
		return *x.Ethnicity
	}
	return ""
}

func (x *SearchIdentityResponse) GetNationalId() string {
	if x != nil && x.NationalId != nil {
		return *x.NationalId
	}
	return ""
}

func (x *SearchIdentityResponse) GetPassportNumber() string {
	if x != nil && x.PassportNumber != nil {
		return *x.PassportNumber
	}
	return ""
}

func (x *SearchIdentityResponse) GetSex() common.Gender {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return common.Gender(0)
}

func (x *SearchIdentityResponse) GetHeightInCm() uint32 {
	if x != nil && x.HeightInCm != nil {
		return *x.HeightInCm
	}
	return 0
}

func (x *SearchIdentityResponse) GetBirthPlaceProvince() string {
	if x != nil && x.BirthPlaceProvince != nil {
		return *x.BirthPlaceProvince
	}
	return ""
}

func (x *SearchIdentityResponse) GetBirthPlaceDistrict() string {
	if x != nil && x.BirthPlaceDistrict != nil {
		return *x.BirthPlaceDistrict
	}
	return ""
}

func (x *SearchIdentityResponse) GetBirthPlaceCommune() string {
	if x != nil && x.BirthPlaceCommune != nil {
		return *x.BirthPlaceCommune
	}
	return ""
}

func (x *SearchIdentityResponse) GetBirthPlaceVillage() string {
	if x != nil && x.BirthPlaceVillage != nil {
		return *x.BirthPlaceVillage
	}
	return ""
}

func (x *SearchIdentityResponse) GetBirthPlaceHouseLabel() string {
	if x != nil && x.BirthPlaceHouseLabel != nil {
		return *x.BirthPlaceHouseLabel
	}
	return ""
}

func (x *SearchIdentityResponse) GetBirthPlaceStreetLabel() string {
	if x != nil && x.BirthPlaceStreetLabel != nil {
		return *x.BirthPlaceStreetLabel
	}
	return ""
}

func (x *SearchIdentityResponse) GetCurrentLivingAddressProvince() string {
	if x != nil && x.CurrentLivingAddressProvince != nil {
		return *x.CurrentLivingAddressProvince
	}
	return ""
}

func (x *SearchIdentityResponse) GetCurrentLivingAddressDistrict() string {
	if x != nil && x.CurrentLivingAddressDistrict != nil {
		return *x.CurrentLivingAddressDistrict
	}
	return ""
}

func (x *SearchIdentityResponse) GetCurrentLivingAddressCommune() string {
	if x != nil && x.CurrentLivingAddressCommune != nil {
		return *x.CurrentLivingAddressCommune
	}
	return ""
}

func (x *SearchIdentityResponse) GetCurrentLivingAddressVillage() string {
	if x != nil && x.CurrentLivingAddressVillage != nil {
		return *x.CurrentLivingAddressVillage
	}
	return ""
}

func (x *SearchIdentityResponse) GetCurrentLivingAddressHouseLabel() string {
	if x != nil && x.CurrentLivingAddressHouseLabel != nil {
		return *x.CurrentLivingAddressHouseLabel
	}
	return ""
}

func (x *SearchIdentityResponse) GetCurrentLivingAddressStreetLabel() string {
	if x != nil && x.CurrentLivingAddressStreetLabel != nil {
		return *x.CurrentLivingAddressStreetLabel
	}
	return ""
}

func (x *SearchIdentityResponse) GetProfileImageDownloadUrl() string {
	if x != nil && x.ProfileImageDownloadUrl != nil {
		return *x.ProfileImageDownloadUrl
	}
	return ""
}

var File_gdi_apis_v0_identity_proto protoreflect.FileDescriptor

const file_gdi_apis_v0_identity_proto_rawDesc = "" +
	"\n" +
	"\x1agdi/apis/v0/identity.proto\x12\vgdi.apis.v0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17gdi/common/gender.proto\"\x94\n" +
	"\n" +
	"\x15SearchIdentityRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x02 \x01(\rH\x01R\x03age\x88\x01\x01\x12%\n" +
	"\fheight_in_cm\x18\x03 \x01(\rH\x02R\n" +
	"heightInCm\x88\x01\x01\x12/\n" +
	"\x06gender\x18\x04 \x01(\x0e2\x12.gdi.common.GenderH\x03R\x06gender\x88\x01\x01\x12+\n" +
	"\x0fleft_face_image\x18\x05 \x01(\fH\x04R\rleftFaceImage\x88\x01\x01\x12-\n" +
	"\x10front_face_image\x18\x06 \x01(\fH\x05R\x0efrontFaceImage\x88\x01\x01\x12-\n" +
	"\x10right_face_image\x18\a \x01(\fH\x06R\x0erightFaceImage\x88\x01\x01\x12:\n" +
	"\x17left_pinky_finger_image\x18\b \x01(\fH\aR\x14leftPinkyFingerImage\x88\x01\x01\x128\n" +
	"\x16left_ring_finger_image\x18\t \x01(\fH\bR\x13leftRingFingerImage\x88\x01\x01\x12<\n" +
	"\x18left_middle_finger_image\x18\n" +
	" \x01(\fH\tR\x15leftMiddleFingerImage\x88\x01\x01\x12:\n" +
	"\x17left_index_finger_image\x18\v \x01(\fH\n" +
	"R\x14leftIndexFingerImage\x88\x01\x01\x12:\n" +
	"\x17left_thumb_finger_image\x18\f \x01(\fH\vR\x14leftThumbFingerImage\x88\x01\x01\x12<\n" +
	"\x18right_pinky_finger_image\x18\r \x01(\fH\fR\x15rightPinkyFingerImage\x88\x01\x01\x12:\n" +
	"\x17right_ring_finger_image\x18\x0e \x01(\fH\rR\x14rightRingFingerImage\x88\x01\x01\x12>\n" +
	"\x19right_middle_finger_image\x18\x0f \x01(\fH\x0eR\x16rightMiddleFingerImage\x88\x01\x01\x12<\n" +
	"\x18right_index_finger_image\x18\x10 \x01(\fH\x0fR\x15rightIndexFingerImage\x88\x01\x01\x12<\n" +
	"\x18right_thumb_finger_image\x18\x11 \x01(\fH\x10R\x15rightThumbFingerImage\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_ageB\x0f\n" +
	"\r_height_in_cmB\t\n" +
	"\a_genderB\x12\n" +
	"\x10_left_face_imageB\x13\n" +
	"\x11_front_face_imageB\x13\n" +
	"\x11_right_face_imageB\x1a\n" +
	"\x18_left_pinky_finger_imageB\x19\n" +
	"\x17_left_ring_finger_imageB\x1b\n" +
	"\x19_left_middle_finger_imageB\x1a\n" +
	"\x18_left_index_finger_imageB\x1a\n" +
	"\x18_left_thumb_finger_imageB\x1b\n" +
	"\x19_right_pinky_finger_imageB\x1a\n" +
	"\x18_right_ring_finger_imageB\x1c\n" +
	"\x1a_right_middle_finger_imageB\x1b\n" +
	"\x19_right_index_finger_imageB\x1b\n" +
	"\x19_right_thumb_finger_image\"\x93\x11\n" +
	"\x16SearchIdentityResponse\x12'\n" +
	"\rlast_name_khm\x18\x01 \x01(\tH\x00R\vlastNameKhm\x88\x01\x01\x12)\n" +
	"\x0efirst_name_khm\x18\x02 \x01(\tH\x01R\ffirstNameKhm\x88\x01\x01\x12'\n" +
	"\rlast_name_eng\x18\x03 \x01(\tH\x02R\vlastNameEng\x88\x01\x01\x12)\n" +
	"\x0efirst_name_eng\x18\x04 \x01(\tH\x03R\ffirstNameEng\x88\x01\x01\x12%\n" +
	"\fweight_in_kg\x18\x05 \x01(\rH\x04R\n" +
	"weightInKg\x88\x01\x01\x12U\n" +
	"$distinguishable_features_description\x18\x06 \x01(\tH\x05R\"distinguishableFeaturesDescription\x88\x01\x01\x12C\n" +
	"\rdate_of_birth\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x06R\vdateOfBirth\x88\x01\x01\x12G\n" +
	"\x1dnationality_in_iso31661alpha3\x18\b \x01(\tH\aR\x1bnationalityInIso31661alpha3\x88\x01\x01\x12!\n" +
	"\tethnicity\x18\t \x01(\tH\bR\tethnicity\x88\x01\x01\x12$\n" +
	"\vnational_id\x18\n" +
	" \x01(\tH\tR\n" +
	"nationalId\x88\x01\x01\x12,\n" +
	"\x0fpassport_number\x18\v \x01(\tH\n" +
	"R\x0epassportNumber\x88\x01\x01\x12)\n" +
	"\x03sex\x18\f \x01(\x0e2\x12.gdi.common.GenderH\vR\x03sex\x88\x01\x01\x12%\n" +
	"\fheight_in_cm\x18\r \x01(\rH\fR\n" +
	"heightInCm\x88\x01\x01\x125\n" +
	"\x14birth_place_province\x18\x0e \x01(\tH\rR\x12birthPlaceProvince\x88\x01\x01\x125\n" +
	"\x14birth_place_district\x18\x0f \x01(\tH\x0eR\x12birthPlaceDistrict\x88\x01\x01\x123\n" +
	"\x13birth_place_commune\x18\x10 \x01(\tH\x0fR\x11birthPlaceCommune\x88\x01\x01\x123\n" +
	"\x13birth_place_village\x18\x11 \x01(\tH\x10R\x11birthPlaceVillage\x88\x01\x01\x12:\n" +
	"\x17birth_place_house_label\x18\x12 \x01(\tH\x11R\x14birthPlaceHouseLabel\x88\x01\x01\x12<\n" +
	"\x18birth_place_street_label\x18\x13 \x01(\tH\x12R\x15birthPlaceStreetLabel\x88\x01\x01\x12J\n" +
	"\x1fcurrent_living_address_province\x18\x14 \x01(\tH\x13R\x1ccurrentLivingAddressProvince\x88\x01\x01\x12J\n" +
	"\x1fcurrent_living_address_district\x18\x15 \x01(\tH\x14R\x1ccurrentLivingAddressDistrict\x88\x01\x01\x12H\n" +
	"\x1ecurrent_living_address_commune\x18\x16 \x01(\tH\x15R\x1bcurrentLivingAddressCommune\x88\x01\x01\x12H\n" +
	"\x1ecurrent_living_address_village\x18\x17 \x01(\tH\x16R\x1bcurrentLivingAddressVillage\x88\x01\x01\x12O\n" +
	"\"current_living_address_house_label\x18\x18 \x01(\tH\x17R\x1ecurrentLivingAddressHouseLabel\x88\x01\x01\x12Q\n" +
	"#current_living_address_street_label\x18\x19 \x01(\tH\x18R\x1fcurrentLivingAddressStreetLabel\x88\x01\x01\x12@\n" +
	"\x1aprofile_image_download_url\x18\x1a \x01(\tH\x19R\x17profileImageDownloadUrl\x88\x01\x01B\x10\n" +
	"\x0e_last_name_khmB\x11\n" +
	"\x0f_first_name_khmB\x10\n" +
	"\x0e_last_name_engB\x11\n" +
	"\x0f_first_name_engB\x0f\n" +
	"\r_weight_in_kgB'\n" +
	"%_distinguishable_features_descriptionB\x10\n" +
	"\x0e_date_of_birthB \n" +
	"\x1e_nationality_in_iso31661alpha3B\f\n" +
	"\n" +
	"_ethnicityB\x0e\n" +
	"\f_national_idB\x12\n" +
	"\x10_passport_numberB\x06\n" +
	"\x04_sexB\x0f\n" +
	"\r_height_in_cmB\x17\n" +
	"\x15_birth_place_provinceB\x17\n" +
	"\x15_birth_place_districtB\x16\n" +
	"\x14_birth_place_communeB\x16\n" +
	"\x14_birth_place_villageB\x1a\n" +
	"\x18_birth_place_house_labelB\x1b\n" +
	"\x19_birth_place_street_labelB\"\n" +
	" _current_living_address_provinceB\"\n" +
	" _current_living_address_districtB!\n" +
	"\x1f_current_living_address_communeB!\n" +
	"\x1f_current_living_address_villageB%\n" +
	"#_current_living_address_house_labelB&\n" +
	"$_current_living_address_street_labelB\x1d\n" +
	"\x1b_profile_image_download_url2e\n" +
	"\bIdentity\x12Y\n" +
	"\x0eSearchIdentity\x12\".gdi.apis.v0.SearchIdentityRequest\x1a#.gdi.apis.v0.SearchIdentityResponseb\x06proto3"

var (
	file_gdi_apis_v0_identity_proto_rawDescOnce sync.Once
	file_gdi_apis_v0_identity_proto_rawDescData []byte
)

func file_gdi_apis_v0_identity_proto_rawDescGZIP() []byte {
	file_gdi_apis_v0_identity_proto_rawDescOnce.Do(func() {
		file_gdi_apis_v0_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gdi_apis_v0_identity_proto_rawDesc), len(file_gdi_apis_v0_identity_proto_rawDesc)))
	})
	return file_gdi_apis_v0_identity_proto_rawDescData
}

var file_gdi_apis_v0_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gdi_apis_v0_identity_proto_goTypes = []any{
	(*SearchIdentityRequest)(nil),  // 0: gdi.apis.v0.SearchIdentityRequest
	(*SearchIdentityResponse)(nil), // 1: gdi.apis.v0.SearchIdentityResponse
	(common.Gender)(0),             // 2: gdi.common.Gender
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_gdi_apis_v0_identity_proto_depIdxs = []int32{
	2, // 0: gdi.apis.v0.SearchIdentityRequest.gender:type_name -> gdi.common.Gender
	3, // 1: gdi.apis.v0.SearchIdentityResponse.date_of_birth:type_name -> google.protobuf.Timestamp
	2, // 2: gdi.apis.v0.SearchIdentityResponse.sex:type_name -> gdi.common.Gender
	0, // 3: gdi.apis.v0.Identity.SearchIdentity:input_type -> gdi.apis.v0.SearchIdentityRequest
	1, // 4: gdi.apis.v0.Identity.SearchIdentity:output_type -> gdi.apis.v0.SearchIdentityResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gdi_apis_v0_identity_proto_init() }
func file_gdi_apis_v0_identity_proto_init() {
	if File_gdi_apis_v0_identity_proto != nil {
		return
	}
	file_gdi_apis_v0_identity_proto_msgTypes[0].OneofWrappers = []any{}
	file_gdi_apis_v0_identity_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gdi_apis_v0_identity_proto_rawDesc), len(file_gdi_apis_v0_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gdi_apis_v0_identity_proto_goTypes,
		DependencyIndexes: file_gdi_apis_v0_identity_proto_depIdxs,
		MessageInfos:      file_gdi_apis_v0_identity_proto_msgTypes,
	}.Build()
	File_gdi_apis_v0_identity_proto = out.File
	file_gdi_apis_v0_identity_proto_goTypes = nil
	file_gdi_apis_v0_identity_proto_depIdxs = nil
}
