// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cms/apis/v0/blacklist.proto

package v0

import (
	v0 "github.com/EKYCSolutions/cms-integration-api/proto/cms/common/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchBlacklistRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Filter        *v0.SearchRequestFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      uint32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    uint32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBlacklistRequest) Reset() {
	*x = SearchBlacklistRequest{}
	mi := &file_cms_apis_v0_blacklist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBlacklistRequest) ProtoMessage() {}

func (x *SearchBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_apis_v0_blacklist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBlacklistRequest.ProtoReflect.Descriptor instead.
func (*SearchBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_cms_apis_v0_blacklist_proto_rawDescGZIP(), []int{0}
}

func (x *SearchBlacklistRequest) GetFilter() *v0.SearchRequestFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchBlacklistRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchBlacklistRequest) GetPageNumber() uint32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type SearchBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMatches  uint32                 `protobuf:"varint,1,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	Data          []*BlacklistData       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBlacklistResponse) Reset() {
	*x = SearchBlacklistResponse{}
	mi := &file_cms_apis_v0_blacklist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBlacklistResponse) ProtoMessage() {}

func (x *SearchBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cms_apis_v0_blacklist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBlacklistResponse.ProtoReflect.Descriptor instead.
func (*SearchBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_cms_apis_v0_blacklist_proto_rawDescGZIP(), []int{1}
}

func (x *SearchBlacklistResponse) GetTotalMatches() uint32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *SearchBlacklistResponse) GetData() []*BlacklistData {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlacklistData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonalInfo      *v0.PersonalInfo       `protobuf:"bytes,2,opt,name=personal_info,json=personalInfo,proto3,oneof" json:"personal_info,omitempty"`
	BiometricInfo     *v0.BiometricInfo      `protobuf:"bytes,3,opt,name=biometric_info,json=biometricInfo,proto3,oneof" json:"biometric_info,omitempty"`
	Reason            *string                `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	BlacklistDatetime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=blacklist_datetime,json=blacklistDatetime,proto3,oneof" json:"blacklist_datetime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlacklistData) Reset() {
	*x = BlacklistData{}
	mi := &file_cms_apis_v0_blacklist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistData) ProtoMessage() {}

func (x *BlacklistData) ProtoReflect() protoreflect.Message {
	mi := &file_cms_apis_v0_blacklist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistData.ProtoReflect.Descriptor instead.
func (*BlacklistData) Descriptor() ([]byte, []int) {
	return file_cms_apis_v0_blacklist_proto_rawDescGZIP(), []int{2}
}

func (x *BlacklistData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlacklistData) GetPersonalInfo() *v0.PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *BlacklistData) GetBiometricInfo() *v0.BiometricInfo {
	if x != nil {
		return x.BiometricInfo
	}
	return nil
}

func (x *BlacklistData) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *BlacklistData) GetBlacklistDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.BlacklistDatetime
	}
	return nil
}

var File_cms_apis_v0_blacklist_proto protoreflect.FileDescriptor

const file_cms_apis_v0_blacklist_proto_rawDesc = "" +
	"\n" +
	"\x1bcms/apis/v0/blacklist.proto\x12\n" +
	"cms.api.v0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!cms/common/v0/personal_info.proto\x1a\"cms/common/v0/biometric_info.proto\x1a)cms/common/v0/search_request_filter.proto\"\x92\x01\n" +
	"\x16SearchBlacklistRequest\x12:\n" +
	"\x06filter\x18\x01 \x01(\v2\".cms.common.v0.SearchRequestFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\rR\n" +
	"pageNumber\"m\n" +
	"\x17SearchBlacklistResponse\x12#\n" +
	"\rtotal_matches\x18\x01 \x01(\rR\ftotalMatches\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.cms.api.v0.BlacklistDataR\x04data\"\xe4\x02\n" +
	"\rBlacklistData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\rpersonal_info\x18\x02 \x01(\v2\x1b.cms.common.v0.PersonalInfoH\x00R\fpersonalInfo\x88\x01\x01\x12H\n" +
	"\x0ebiometric_info\x18\x03 \x01(\v2\x1c.cms.common.v0.BiometricInfoH\x01R\rbiometricInfo\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x04 \x01(\tH\x02R\x06reason\x88\x01\x01\x12N\n" +
	"\x12blacklist_datetime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x11blacklistDatetime\x88\x01\x01B\x10\n" +
	"\x0e_personal_infoB\x11\n" +
	"\x0f_biometric_infoB\t\n" +
	"\a_reasonB\x15\n" +
	"\x13_blacklist_datetime2g\n" +
	"\tBlacklist\x12Z\n" +
	"\x0fSearchBlacklist\x12\".cms.api.v0.SearchBlacklistRequest\x1a#.cms.api.v0.SearchBlacklistResponseb\x06proto3"

var (
	file_cms_apis_v0_blacklist_proto_rawDescOnce sync.Once
	file_cms_apis_v0_blacklist_proto_rawDescData []byte
)

func file_cms_apis_v0_blacklist_proto_rawDescGZIP() []byte {
	file_cms_apis_v0_blacklist_proto_rawDescOnce.Do(func() {
		file_cms_apis_v0_blacklist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_apis_v0_blacklist_proto_rawDesc), len(file_cms_apis_v0_blacklist_proto_rawDesc)))
	})
	return file_cms_apis_v0_blacklist_proto_rawDescData
}

var file_cms_apis_v0_blacklist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cms_apis_v0_blacklist_proto_goTypes = []any{
	(*SearchBlacklistRequest)(nil),  // 0: cms.api.v0.SearchBlacklistRequest
	(*SearchBlacklistResponse)(nil), // 1: cms.api.v0.SearchBlacklistResponse
	(*BlacklistData)(nil),           // 2: cms.api.v0.BlacklistData
	(*v0.SearchRequestFilter)(nil),  // 3: cms.common.v0.SearchRequestFilter
	(*v0.PersonalInfo)(nil),         // 4: cms.common.v0.PersonalInfo
	(*v0.BiometricInfo)(nil),        // 5: cms.common.v0.BiometricInfo
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_cms_apis_v0_blacklist_proto_depIdxs = []int32{
	3, // 0: cms.api.v0.SearchBlacklistRequest.filter:type_name -> cms.common.v0.SearchRequestFilter
	2, // 1: cms.api.v0.SearchBlacklistResponse.data:type_name -> cms.api.v0.BlacklistData
	4, // 2: cms.api.v0.BlacklistData.personal_info:type_name -> cms.common.v0.PersonalInfo
	5, // 3: cms.api.v0.BlacklistData.biometric_info:type_name -> cms.common.v0.BiometricInfo
	6, // 4: cms.api.v0.BlacklistData.blacklist_datetime:type_name -> google.protobuf.Timestamp
	0, // 5: cms.api.v0.Blacklist.SearchBlacklist:input_type -> cms.api.v0.SearchBlacklistRequest
	1, // 6: cms.api.v0.Blacklist.SearchBlacklist:output_type -> cms.api.v0.SearchBlacklistResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cms_apis_v0_blacklist_proto_init() }
func file_cms_apis_v0_blacklist_proto_init() {
	if File_cms_apis_v0_blacklist_proto != nil {
		return
	}
	file_cms_apis_v0_blacklist_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_apis_v0_blacklist_proto_rawDesc), len(file_cms_apis_v0_blacklist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cms_apis_v0_blacklist_proto_goTypes,
		DependencyIndexes: file_cms_apis_v0_blacklist_proto_depIdxs,
		MessageInfos:      file_cms_apis_v0_blacklist_proto_msgTypes,
	}.Build()
	File_cms_apis_v0_blacklist_proto = out.File
	file_cms_apis_v0_blacklist_proto_goTypes = nil
	file_cms_apis_v0_blacklist_proto_depIdxs = nil
}
