// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: cms/apis/v0/blacklist.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blacklist_SearchBlacklist_FullMethodName = "/cms.api.v0.Blacklist/SearchBlacklist"
)

// BlacklistClient is the client API for Blacklist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlacklistClient interface {
	SearchBlacklist(ctx context.Context, in *SearchBlacklistRequest, opts ...grpc.CallOption) (*SearchBlacklistResponse, error)
}

type blacklistClient struct {
	cc grpc.ClientConnInterface
}

func NewBlacklistClient(cc grpc.ClientConnInterface) BlacklistClient {
	return &blacklistClient{cc}
}

func (c *blacklistClient) SearchBlacklist(ctx context.Context, in *SearchBlacklistRequest, opts ...grpc.CallOption) (*SearchBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBlacklistResponse)
	err := c.cc.Invoke(ctx, Blacklist_SearchBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlacklistServer is the server API for Blacklist service.
// All implementations must embed UnimplementedBlacklistServer
// for forward compatibility.
type BlacklistServer interface {
	SearchBlacklist(context.Context, *SearchBlacklistRequest) (*SearchBlacklistResponse, error)
	mustEmbedUnimplementedBlacklistServer()
}

// UnimplementedBlacklistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlacklistServer struct{}

func (UnimplementedBlacklistServer) SearchBlacklist(context.Context, *SearchBlacklistRequest) (*SearchBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBlacklist not implemented")
}
func (UnimplementedBlacklistServer) mustEmbedUnimplementedBlacklistServer() {}
func (UnimplementedBlacklistServer) testEmbeddedByValue()                   {}

// UnsafeBlacklistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlacklistServer will
// result in compilation errors.
type UnsafeBlacklistServer interface {
	mustEmbedUnimplementedBlacklistServer()
}

func RegisterBlacklistServer(s grpc.ServiceRegistrar, srv BlacklistServer) {
	// If the following call pancis, it indicates UnimplementedBlacklistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blacklist_ServiceDesc, srv)
}

func _Blacklist_SearchBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServer).SearchBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blacklist_SearchBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServer).SearchBlacklist(ctx, req.(*SearchBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blacklist_ServiceDesc is the grpc.ServiceDesc for Blacklist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blacklist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cms.api.v0.Blacklist",
	HandlerType: (*BlacklistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchBlacklist",
			Handler:    _Blacklist_SearchBlacklist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms/apis/v0/blacklist.proto",
}
