// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cms/apis/v0/identity.proto

package v0

import (
	common "github.com/EKYCSolutions/cms-integration-api/proto/cms/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterIdentityRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdentityId        string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Age               uint32                 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	HeightInCm        uint32                 `protobuf:"varint,3,opt,name=height_in_cm,json=heightInCm,proto3" json:"height_in_cm,omitempty"`
	Gender            common.Gender          `protobuf:"varint,4,opt,name=gender,proto3,enum=cms.common.Gender" json:"gender,omitempty"`
	LeftFace          []byte                 `protobuf:"bytes,5,opt,name=left_face,json=leftFace,proto3,oneof" json:"left_face,omitempty"`
	FrontFace         []byte                 `protobuf:"bytes,6,opt,name=front_face,json=frontFace,proto3,oneof" json:"front_face,omitempty"`
	RightFace         []byte                 `protobuf:"bytes,7,opt,name=right_face,json=rightFace,proto3,oneof" json:"right_face,omitempty"`
	LeftPinkyFinger   []byte                 `protobuf:"bytes,8,opt,name=left_pinky_finger,json=leftPinkyFinger,proto3,oneof" json:"left_pinky_finger,omitempty"`
	LeftRingFinger    []byte                 `protobuf:"bytes,9,opt,name=left_ring_finger,json=leftRingFinger,proto3,oneof" json:"left_ring_finger,omitempty"`
	LeftMiddleFinger  []byte                 `protobuf:"bytes,10,opt,name=left_middle_finger,json=leftMiddleFinger,proto3,oneof" json:"left_middle_finger,omitempty"`
	LeftIndexFinger   []byte                 `protobuf:"bytes,11,opt,name=left_index_finger,json=leftIndexFinger,proto3,oneof" json:"left_index_finger,omitempty"`
	LeftThumbFinger   []byte                 `protobuf:"bytes,12,opt,name=left_thumb_finger,json=leftThumbFinger,proto3,oneof" json:"left_thumb_finger,omitempty"`
	RightPinkyFinger  []byte                 `protobuf:"bytes,13,opt,name=right_pinky_finger,json=rightPinkyFinger,proto3,oneof" json:"right_pinky_finger,omitempty"`
	RightRingFinger   []byte                 `protobuf:"bytes,14,opt,name=right_ring_finger,json=rightRingFinger,proto3,oneof" json:"right_ring_finger,omitempty"`
	RightMiddleFinger []byte                 `protobuf:"bytes,15,opt,name=right_middle_finger,json=rightMiddleFinger,proto3,oneof" json:"right_middle_finger,omitempty"`
	RightIndexFinger  []byte                 `protobuf:"bytes,16,opt,name=right_index_finger,json=rightIndexFinger,proto3,oneof" json:"right_index_finger,omitempty"`
	RightThumbFinger  []byte                 `protobuf:"bytes,17,opt,name=right_thumb_finger,json=rightThumbFinger,proto3,oneof" json:"right_thumb_finger,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterIdentityRequest) Reset() {
	*x = RegisterIdentityRequest{}
	mi := &file_cms_apis_v0_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityRequest) ProtoMessage() {}

func (x *RegisterIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cms_apis_v0_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityRequest.ProtoReflect.Descriptor instead.
func (*RegisterIdentityRequest) Descriptor() ([]byte, []int) {
	return file_cms_apis_v0_identity_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterIdentityRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *RegisterIdentityRequest) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterIdentityRequest) GetHeightInCm() uint32 {
	if x != nil {
		return x.HeightInCm
	}
	return 0
}

func (x *RegisterIdentityRequest) GetGender() common.Gender {
	if x != nil {
		return x.Gender
	}
	return common.Gender(0)
}

func (x *RegisterIdentityRequest) GetLeftFace() []byte {
	if x != nil {
		return x.LeftFace
	}
	return nil
}

func (x *RegisterIdentityRequest) GetFrontFace() []byte {
	if x != nil {
		return x.FrontFace
	}
	return nil
}

func (x *RegisterIdentityRequest) GetRightFace() []byte {
	if x != nil {
		return x.RightFace
	}
	return nil
}

func (x *RegisterIdentityRequest) GetLeftPinkyFinger() []byte {
	if x != nil {
		return x.LeftPinkyFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetLeftRingFinger() []byte {
	if x != nil {
		return x.LeftRingFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetLeftMiddleFinger() []byte {
	if x != nil {
		return x.LeftMiddleFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetLeftIndexFinger() []byte {
	if x != nil {
		return x.LeftIndexFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetLeftThumbFinger() []byte {
	if x != nil {
		return x.LeftThumbFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetRightPinkyFinger() []byte {
	if x != nil {
		return x.RightPinkyFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetRightRingFinger() []byte {
	if x != nil {
		return x.RightRingFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetRightMiddleFinger() []byte {
	if x != nil {
		return x.RightMiddleFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetRightIndexFinger() []byte {
	if x != nil {
		return x.RightIndexFinger
	}
	return nil
}

func (x *RegisterIdentityRequest) GetRightThumbFinger() []byte {
	if x != nil {
		return x.RightThumbFinger
	}
	return nil
}

type RegisterIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIdentityResponse) Reset() {
	*x = RegisterIdentityResponse{}
	mi := &file_cms_apis_v0_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityResponse) ProtoMessage() {}

func (x *RegisterIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cms_apis_v0_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityResponse.ProtoReflect.Descriptor instead.
func (*RegisterIdentityResponse) Descriptor() ([]byte, []int) {
	return file_cms_apis_v0_identity_proto_rawDescGZIP(), []int{1}
}

var File_cms_apis_v0_identity_proto protoreflect.FileDescriptor

const file_cms_apis_v0_identity_proto_rawDesc = "" +
	"\n" +
	"\x1acms/apis/v0/identity.proto\x12\vcms.apis.v0\x1a\x17cms/common/gender.proto\"\x85\b\n" +
	"\x17RegisterIdentityRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x10\n" +
	"\x03age\x18\x02 \x01(\rR\x03age\x12 \n" +
	"\fheight_in_cm\x18\x03 \x01(\rR\n" +
	"heightInCm\x12*\n" +
	"\x06gender\x18\x04 \x01(\x0e2\x12.cms.common.GenderR\x06gender\x12 \n" +
	"\tleft_face\x18\x05 \x01(\fH\x00R\bleftFace\x88\x01\x01\x12\"\n" +
	"\n" +
	"front_face\x18\x06 \x01(\fH\x01R\tfrontFace\x88\x01\x01\x12\"\n" +
	"\n" +
	"right_face\x18\a \x01(\fH\x02R\trightFace\x88\x01\x01\x12/\n" +
	"\x11left_pinky_finger\x18\b \x01(\fH\x03R\x0fleftPinkyFinger\x88\x01\x01\x12-\n" +
	"\x10left_ring_finger\x18\t \x01(\fH\x04R\x0eleftRingFinger\x88\x01\x01\x121\n" +
	"\x12left_middle_finger\x18\n" +
	" \x01(\fH\x05R\x10leftMiddleFinger\x88\x01\x01\x12/\n" +
	"\x11left_index_finger\x18\v \x01(\fH\x06R\x0fleftIndexFinger\x88\x01\x01\x12/\n" +
	"\x11left_thumb_finger\x18\f \x01(\fH\aR\x0fleftThumbFinger\x88\x01\x01\x121\n" +
	"\x12right_pinky_finger\x18\r \x01(\fH\bR\x10rightPinkyFinger\x88\x01\x01\x12/\n" +
	"\x11right_ring_finger\x18\x0e \x01(\fH\tR\x0frightRingFinger\x88\x01\x01\x123\n" +
	"\x13right_middle_finger\x18\x0f \x01(\fH\n" +
	"R\x11rightMiddleFinger\x88\x01\x01\x121\n" +
	"\x12right_index_finger\x18\x10 \x01(\fH\vR\x10rightIndexFinger\x88\x01\x01\x121\n" +
	"\x12right_thumb_finger\x18\x11 \x01(\fH\fR\x10rightThumbFinger\x88\x01\x01B\f\n" +
	"\n" +
	"_left_faceB\r\n" +
	"\v_front_faceB\r\n" +
	"\v_right_faceB\x14\n" +
	"\x12_left_pinky_fingerB\x13\n" +
	"\x11_left_ring_fingerB\x15\n" +
	"\x13_left_middle_fingerB\x14\n" +
	"\x12_left_index_fingerB\x14\n" +
	"\x12_left_thumb_fingerB\x15\n" +
	"\x13_right_pinky_fingerB\x14\n" +
	"\x12_right_ring_fingerB\x16\n" +
	"\x14_right_middle_fingerB\x15\n" +
	"\x13_right_index_fingerB\x15\n" +
	"\x13_right_thumb_finger\"\x1a\n" +
	"\x18RegisterIdentityResponse2k\n" +
	"\bIdentity\x12_\n" +
	"\x10RegisterIdentity\x12$.cms.apis.v0.RegisterIdentityRequest\x1a%.cms.apis.v0.RegisterIdentityResponseb\x06proto3"

var (
	file_cms_apis_v0_identity_proto_rawDescOnce sync.Once
	file_cms_apis_v0_identity_proto_rawDescData []byte
)

func file_cms_apis_v0_identity_proto_rawDescGZIP() []byte {
	file_cms_apis_v0_identity_proto_rawDescOnce.Do(func() {
		file_cms_apis_v0_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_apis_v0_identity_proto_rawDesc), len(file_cms_apis_v0_identity_proto_rawDesc)))
	})
	return file_cms_apis_v0_identity_proto_rawDescData
}

var file_cms_apis_v0_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cms_apis_v0_identity_proto_goTypes = []any{
	(*RegisterIdentityRequest)(nil),  // 0: cms.apis.v0.RegisterIdentityRequest
	(*RegisterIdentityResponse)(nil), // 1: cms.apis.v0.RegisterIdentityResponse
	(common.Gender)(0),               // 2: cms.common.Gender
}
var file_cms_apis_v0_identity_proto_depIdxs = []int32{
	2, // 0: cms.apis.v0.RegisterIdentityRequest.gender:type_name -> cms.common.Gender
	0, // 1: cms.apis.v0.Identity.RegisterIdentity:input_type -> cms.apis.v0.RegisterIdentityRequest
	1, // 2: cms.apis.v0.Identity.RegisterIdentity:output_type -> cms.apis.v0.RegisterIdentityResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cms_apis_v0_identity_proto_init() }
func file_cms_apis_v0_identity_proto_init() {
	if File_cms_apis_v0_identity_proto != nil {
		return
	}
	file_cms_apis_v0_identity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_apis_v0_identity_proto_rawDesc), len(file_cms_apis_v0_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cms_apis_v0_identity_proto_goTypes,
		DependencyIndexes: file_cms_apis_v0_identity_proto_depIdxs,
		MessageInfos:      file_cms_apis_v0_identity_proto_msgTypes,
	}.Build()
	File_cms_apis_v0_identity_proto = out.File
	file_cms_apis_v0_identity_proto_goTypes = nil
	file_cms_apis_v0_identity_proto_depIdxs = nil
}
